/* eslint-disable prettier/prettier */
export const en = {
  navigator: {
    home: 'Products',
    cart: 'Cart',
  },
  common: {
    offlineMessage: 'You are offline, only Buying list and Cart features are available',
    noResult: "No Result",
    errorCheckout: 'Something went wrong.',
    productCatalogue: 'Products',
    filter: 'Filter',
    productDetail: 'Product Detail',
    buyingList: 'Buying List',
    products: 'Products',
    seasonal: 'seasonal',
    searchProduct: 'Search Product',
    categories: 'Categories',
    cart: 'Shopping Cart',
    deliverSeparetely: 'Deliver Separately',
    orderDate: 'Order Date',
    totalPrice: 'Total Price',
    subTotal: 'Subtotal',
    price: 'Price',
    addComment: 'Add Comment',
    aboutThisProduct: 'About This Product',
    productCurrentDayRule: '',
    promotionalProduct: 'Promotional Product',
    aboutProduct: 'About the Product',
    features: 'Features',
    distance: 'Distance',
    transport: 'Transport',
    label: 'Label',
    bestBefore: 'Best before',
    seeProductDetails: 'See Product Details',
    itemSheetSpecification: 'Item Sheet / Specification',
    productSpecifications: 'Product Specification',
    artcileNo: 'Article No',
    origin: 'Origin',
    brand: 'Brand',
    packagingInfo: 'Packaging Info',
    relatedProducts: 'Related Products',
    password: 'Password *',
    emailUserName: 'Username or Email Address *',
    notLogin: 'You have not logged in, Please Login',
    noInternet: 'You are not connected to the internet',
    delete: 'Are you sure, you want to delete ?',
    noData: 'No Data',
    orderHistory: 'Order History',
    thankyoufororder: 'Thank you for your purchase',
    clickonme: 'Click on the button to view your order history',
    login: 'Log in',
    orderNumber: 'Order Number',
    orderedOn: 'Ordered on',
    deliverOn: 'Delivered on',
    total: 'Total',
    for: 'for',
    items: 'items',
    selectQuantity: 'Please select quantity',
    selectBuyingList: 'Select Buying List',
    totalProducts: 'Total Products',
    addToCartSuccess: 'Product added to cart successfully',
    logoutMessage: 'Are you sure you want to logout',
    selectUnit: 'Select Unit',
    allCategories: 'All Categories',
    filterOptions: 'Filter Options',
    newProduct: 'New Product',
    promotion: 'Promotional',
    clearAll: 'Clear all',
    seasonality: 'Seasonality',
    copy: 'Copy',
    rename: 'Rename',
    save: 'Save',
    cancel: 'Cancel',
    sortBy: 'Sort by',
    alphabet: 'Alphabet',
    priceLowToHigh: 'Price low to high',
    priceHighToLow: 'Price high to low',
    dietaryHabit: 'Dietary Habit',
    email: 'E-Mail',
    address: 'Address',
    phone: 'Phone',
    contactInfo: 'Contact Information',
    yesNo: 'Yes / No',
    glutenFree: 'Gluten free',
    lactoseFree: 'Lactose free',
    frozen: 'Frozen',
    vegan: 'Vegan',
    veggie: 'Veggie',
  },
  menu: {
    orderDetails: 'Order Details',
    orderHistory: 'Orders History',
    myAccount: 'My Account',
    contactUs: 'Contact Us',
    faqs: 'FAQs',
    helpSupport: 'Help & Support',
    impressum: 'Impressum',
    signOut: 'Sign out',
  },
  createList: {
    createList: 'Create List',
    enterListName: 'Enter List Name',
  },
  actions: {
    addList: 'Add List',
    addCart: 'Add to Cart',
    clearAll: 'Clear All',
    done: 'Done',
    checkout: 'Place an Order',
    login: 'Login',
    yes: 'Yes',
    no: 'No',
    view: 'View',
    reOrder: 'Re-Order',
    print: 'Print',
    // cancel: 'Cancel',
    // rename: 'Rename List',
  },
  chart: {
    swiss: "Swiss",
    europe: "Europe",
    overseas: "Overseas"
  },
  cart: {
    offlineTitle: "You are offline!",
    offlineMessage: "Should the order be sent automatically when you are online again? If yes, confirm the order with YES\nWould you like to submit the order yourself when you are online again? If so, then click NO."
  },
  months: {
    jan: "January",
    feb: "February",
    march: "March",
    april: "April",
    may: "May",
    june: "June",
    july: "July",
    aug: "August",
    sep: "September",
    oct: "October",
    nov: "November",
    dec: "December"
  },

};
