/* eslint-disable prettier/prettier */
const AUTH_ACTION_TYPES = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    TOAST_CLEANUP: 'TOAST_CLEANUP',

    SIGNUP_REQUEST: 'SIGNUP_REQUEST',
    SIGNUP_FAILURE: 'SIGNUP_FAILURE',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    FORGET_PASSWORD_REQUEST: 'FORGET_PASSWORD_REQUEST',
    FORGET_PASSWORD_FAILURE: 'FORGET_PASSWORD_FAILURE',
    FORGET_PASSWORD_SUCCESS: 'FORGET_PASSWORD_SUCCESS',

};
export default AUTH_ACTION_TYPES;
