/* eslint-disable prettier/prettier */
const BUYING_ACTION_TYPES = {
    BUYING_LIST_REQUEST: 'BUYING_LIST_REQUEST',
    BUYING_LIST_FAILURE: 'BUYING_LIST_FAILURE',
    BUYING_LIST_SUCCESS: 'BUYING_LIST_SUCCESS',

    BUYING_CREATE_REQUEST: 'BUYING_CREATE_REQUEST',
    BUYING_CREATE_FAILURE: 'BUYING_CREATE_FAILURE',
    BUYING_CREATE_SUCCESS: 'BUYING_CREATE_SUCCESS',

    BUYING_REMOVE_REQUEST: 'BUYING_REMOVE_REQUEST',
    BUYING_REMOVE_FAILURE: 'BUYING_REMOVE_FAILURE',
    BUYING_REMOVE_SUCCESS: 'BUYING_REMOVE_SUCCESS',

    BUYING_LIST_PRODUCT_REQUEST: 'BUYING_LIST_PRODUCT_REQUEST',
    BUYING_LIST_PRODUCT_FAILURE: 'BUYING_LIST_PRODUCT_FAILURE',
    BUYING_LIST_PRODUCT_SUCCESS: 'BUYING_LIST_PRODUCT_SUCCESS',

    BUYING_REMOVE_PRODUCT_REQUEST: 'BUYING_REMOVE_PRODUCT_REQUEST',
    BUYING_REMOVE_PRODUCT_FAILURE: 'BUYING_REMOVE_PRODUCT_FAILURE',
    BUYING_REMOVE_PRODUCT_SUCCESS: 'BUYING_REMOVE_PRODUCT_SUCCESS',

    CLEAN_UP_BUYING_REQUEST: 'CLEAN_UP_BUYING_REQUEST',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
};
export default BUYING_ACTION_TYPES;
