/* eslint-disable prettier/prettier */
const CART_ACTION_TYPES = {
    CART_LIST_REQUEST: 'CART_LIST_REQUEST',
    CART_LIST_FAILURE: 'CART_LIST_FAILURE',
    CART_LIST_SUCCESS: 'CART_LIST_SUCCESS',

    ADD_CART_BUYING_REQUEST: 'ADD_CART_BUYING_REQUEST',
    ADD_CART_BUYING_FAILURE: 'ADD_CART_BUYING_FAILURE',
    ADD_CART_BUYING_SUCCESS: 'ADD_CART_BUYING_SUCCESS',

    ADD_ITEM_TO_CART_OFFLINE: 'ADD_ITEM_TO_CART_OFFLINE',
    EMPTY_CART_OFFLINE: 'EMPTY_CART_OFFLINE',
    REPLACE_CART_OFFLINE: 'REPLACE_CART_OFFLINE',
    REPLACE_CART_OFFLINE: 'REPLACE_CART_OFFLINE',
    STORE_PLACE_ORDER_STATUS: "STORE_PLACE_ORDER_STATUS",

    CART_REMOVE_REQUEST: 'CART_REMOVE_REQUEST',
    CART_REMOVE_FAILURE: 'CART_REMOVE_FAILURE',
    CART_REMOVE_SUCCESS: 'CART_REMOVE_SUCCESS',

    ORDER_LIST_REQUEST: 'ORDER_LIST_REQUEST',
    ORDER_LIST_FAILURE: 'ORDER_LIST_FAILURE',
    ORDER_LIST_SUCCESS: 'ORDER_LIST_SUCCESS',

    ORDER_LIST_LOAD_REQUEST: 'ORDER_LIST_LOAD_REQUEST',
    ORDER_LIST_LOAD_FAILURE: 'ORDER_LIST_LOAD_FAILURE',
    ORDER_LIST_LOAD_SUCCESS: 'ORDER_LIST_LOAD_SUCCESS',

    PAGE_CART_REQUEST: 'PAGE_CART_REQUEST',

    CLEAN_UP_CART_REQUEST: 'CLEAN_UP_CART_REQUEST',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
};
export default CART_ACTION_TYPES;
