/* eslint-disable prettier/prettier */
const MASTER_ACTION_TYPES = {
    SLIDER_DATA_REQUEST: 'SLIDER_DATA_REQUEST',
    SLIDER_DATA_FAILURE: 'SLIDER_DATA_FAILURE',
    SLIDER_DATA_SUCCESS: 'SLIDER_DATA_SUCCESS',

    SET_STEP: 'SET_STEP',
};
export default MASTER_ACTION_TYPES;
