/* eslint-disable prettier/prettier */
const PRODUCT_ACTION_TYPES = {
  PRODUCT_LIST_REQUEST: 'PRODUCT_LIST_REQUEST',
  PRODUCT_LIST_FAILURE: 'PRODUCT_LIST_FAILURE',
  PRODUCT_LIST_SUCCESS: 'PRODUCT_LIST_SUCCESS',

  PRODUCT_LIST_LOAD_REQUEST: 'PRODUCT_LIST_LOAD_REQUEST',
  PRODUCT_LIST_LOAD_FAILURE: 'PRODUCT_LIST_LOAD_FAILURE',
  PRODUCT_LIST_LOAD_SUCCESS: 'PRODUCT_LIST_LOAD_SUCCESS',

  PRODUCT_LIST_CATEGORY_REQUEST: 'PRODUCT_LIST_CATEGORY_REQUEST',
  PRODUCT_LIST_CATEGORY_FAILURE: 'PRODUCT_LIST_CATEGORY_FAILURE',
  PRODUCT_LIST_CATEGORY_SUCCESS: 'PRODUCT_LIST_CATEGORY_SUCCESS',

  PRODUCT_LIST_SUBCATEGORY_REQUEST: 'PRODUCT_LIST_SUBCATEGORY_REQUEST',
  PRODUCT_LIST_SUBCATEGORY_FAILURE: 'PRODUCT_LIST_SUBCATEGORY_FAILURE',
  PRODUCT_LIST_SUBCATEGORY_SUCCESS: 'PRODUCT_LIST_SUBCATEGORY_SUCCESS',

  NETWORK_REQUEST: 'NETWORK_REQUEST',
  PAGE_REQUEST: 'PAGE_REQUEST',
};
export default PRODUCT_ACTION_TYPES;
